# Crear un array 7x8 lleno de ceros de tipo entero 

In [2]:
ceros = np.zeros((7,8))
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# crea un array 7x8 lleno de ceros salvo la primera fila que seran todos uno

In [3]:
import numpy as np
array = np.zeros((7, 8))
array[0, :] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [4]:
import numpy as np
array = np.zeros((7, 8))
array[-1, :] = np.arange(5, 13)[:8]
print(array)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9. 10. 11. 12.]]
