<center> <h2>Ejercicio 05</h2> </center> 

De la siguiente Matriz:

<img src="https://user-images.githubusercontent.com/19308295/115969585-39509780-a503-11eb-92ac-fd88557e6cfc.png"
    style="width:400px"></img>

* Extraer la matrices de cada color

In [ ]:
import numpy as np 
a=np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15),(16,17,18,19,20),(21,22,23,24,25),(26,27,28,29,30)])
print(a)

In [5]:
# matriz de color azul
matrizazul = (a[2:4,0:2])  # filas 3 y 4 y columnas 1 y 2
print(matrizazul)

[[11 12]
 [16 17]]


In [7]:
# matriz de color rojo
matrizrojo = (a[[0,4,5], 3:5])   # filas 1 , 5 y 6, columnas 5 y 6
print(matrizrojo)

[[ 4  5]
 [24 25]
 [29 30]]


In [10]:
# matriz de color verde
matrizverde = (a[[0,1,2,3],[1,2,3,4]])
print(matrizverde)

[ 2  8 14 20]
