In [1]:
import numpy as np
a=np.array([(1,1,1,1,1),(1,0,0,0,1),(1,0,9,0,1),(1,0,0,0,1),(1,1,1,1,1)])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [4]:
import numpy as np
a=np.array([(9,9,9,9,9),(9,0,0,0,9),(9,0,1,0,9),(9,0,0,0,9),(9,9,9,9,9)])
print(a)

[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]
